---
- hosts: all
  become: true
  vars:
    trusted:
      - '192.168.2.14'
      - '20.197.227.138'
  tasks:
  - name: Flush existing rules
    nftables:
      table: filter
      chain: input
      flush: yes
  - name: Set default policy to drop
    nftables:
      table: filter
      chain: input
      rules: 'drop'
  - name: Allow minimal traffic for services to work
    nftables:
      table: filter
      chain: input
      rules:
      - 'ct state {established, related} accept'
  - name: Allow SSH and ICMP traffic from trusted hosts
    nftables:
      table: filter
      chain: input
      rules:
      - 'ip saddr {{ item }} tcp dport ssh accept'
      - 'ip saddr {{ item }} icmp type {echo-request, echo-reply} accept'
    with_items: '{{ trusted }}'
  - name: Save rules to file
    nftables_save:
      filename: /etc/nftables.conf
  - name: Enable nftables on boot
    file:
      path: /etc/sysconfig/nftables
      state: touch
      owner: root
      group: root
      mode: 0600
    notify:
      - Restart nftables
  - name: Enable nftables service
    systemd:
      name: nftables
      state: started
      enabled: true
  - name: Restart nftables
    systemd:
      name: nftables
      state: restarted
  handlers:
    - name: Restart nftables
      systemd:
        name: nftables
        state: restarted
