---
- hosts: linux
  remote_user: root
  become: yes
  tasks:

    - name: Read users from CSV file and return a list
      community.general.read_csv:
        path: /etc/ansible/users.csv
        fieldnames: uid,username,password,home
        delimiter: ';'
      register: users
      delegate_to: localhost

    - name: Import users from CSV file
      user:
        name: "{{ item.username }}"
        password: "{{ item.password | password_hash('sha512') }}"
        uid: "{{ item.uid }}"
        update_password: on_create
      with_items:
        - '{{users.list}}'
        