---
- hosts: nfs
  remote_user: root
  become: yes

  tasks:

    - name: Install NFS service
      package:
        name: nfs-kernel-server
        state: present
      when: inventory_hostname in groups['nfs']

    - name: Create logical volumes for NFS shares
      lvol:
        vg: debian-vg
        lv: "{{ item.name }}"
        size: "{{ item.size }}"
      loop: "{{ shares }}"

    - name: Format logical volumes for NFS shares
      filesystem:
        fstype: ext4
        dev: "/dev/debian-vg/{{ item.name }}"
      loop: "{{ shares }}"

    - name: Create NFS directory
      file:
        path: /dev/debian-vg/nfs
        state: directory

    - name: Mount NFS shares
      mount:
        path: "/nfs/{{ item.name }}"
        src: "/dev/debian-vg/{{ item.name }}"
        fstype: ext4
        state: mounted
      loop: "{{ shares }}"

    - name: Create exports file for NFS shares
      template:
        src: exports.j2
        dest: /etc/exports
      loop: "{{ shares }}"
      vars:
        share_name: "{{ item.name }}"
        host: "10.22.0.50"

